### ISSUE TITLE
How to install "voom"package

### ISSUE THREAD

**Issue by wangjiaming1503** [slagtermaarten/cyto_inference#1]
I have some problem to reproduce this excellent work.
seems that voom is a package that is hard to find

Reader from Hoekstra, M. E., Slagter, M., Urbanus, J., Toebes, M., Slingerland, N., de Rink, I., Kluin, R. J. C., Nieuwland, M., Kerkhoven, R., Wessels, L. F. A., & Schumacher, T. N. (2024). Distinct spatiotemporal dynamics of CD8+ T cell-derived cytokines in the tumor microenvironment. Cancer Cell, 42(1), 157-167.e159. https://doi.org/10.1016/j.ccell.2023.12.010 

cit_pkgs <- c('devtools', 'ComplexHeatmap', 'credentials', 'milo', 'sctransform', **'voom**', 'glmnet')
pkgs <- c('miloR', 'car',
  'parsnip', 'tidymodels', 'yardstick', 'ranger', 'kknn', 
  'devtools', 'curl', 'targets', 'ggpubr', 'ArrayExpress',
  'umap', 'progressr', 'rsample', 
  'Hmisc', 
  'glmnet',
  'preprocessCore', 'envnames', 'voom',
  'pracma', 'targets', 
  'DESeq2', 'wesanderson',
  'biomaRt', 'furrr', 'fgsea', 'naturalsort',
  'tidyverse', 'knitr', 
  'tikzDevice',
  'scran', 'SingleCellExperiment', 'limma', 'edgeR', 'ROCR',
  'devtools', 'Seurat', 'GGally', 'knitr', 'pacman', 'circlize',
  'NMF', 'e1071')
already_cited <- c('targets', 'glmnet', 'milo', 'sctransform', 'voom')

for (p in pkgs) {
  try_install(p)
}

# U_lib_dir <- if (dir.exists('~/libs')) '~/libs' else '/u_libs'
if (F && !require('credentials', character.only = T, quietly = T)) {
  remotes::install_github("r-lib/credentials", lib = R_lib_dir)
}

if (!require('ComplexHeatmap', character.only = T, quietly = T)) {
  install_github('Jokergoo/ComplexHeatmap')
  library(ComplexHeatmap)
}

if (!require('maartenutils', character.only = T, quietly = T)) {
  install_github('slagtermaarten/maartenutils')
}

if (!require('genesets', character.only = T, quietly = T)) {
  install_github('slagtermaarten/genesets')
}

**Comment by slagtermaarten** [comment]
The correct package should have been edgeR as it contains voom. I addressed this just now, thanks, and sorry for the inconvenience!
